### ISSUE TITLE
Rotating the screen while selecting apps for notification will lose selection

### ISSUE THREAD

**Issue by sjl872964789** [jroal/a2dpvolume#291] opened 2020-06-02 05:58 UTC
**Describe the bug**
Rotating the screen while selecting app for notification will lose selection

**To Reproduce**
1. Install a2dp and open app
2. Click three points in the upper right corner
3. Click "Apps for notification"
4. Rotate screen
4. Lose selection

**Expected behavior**
will not lose selection

**Smartphone (please complete the following information):**
 - Device: HUAWEI nova 5 pro
 - OS: EMUI 9.1.1
 - Rooted: No
 - Version: v2.13.0.4

**Additional context**

**Comment by jroal** [comment] 2020-06-09 11:23
Yeah, I know I have screen rotation issues but they are low priority as you use configuration screens very rarely and most don't rotate while using them.  I am one guy writing this app for my own use and making it available to everyone for free, no ads. I do this in my spare time.  I just don't plan to invest any time in screen rotation issues.  I would happily implement a fix if someone could do the work of figuring out what I need to change to correct these issues.  If you want this foxed (and the other 2 rotation issues you posted) please investigate it, find a fix, and explain it to me so I can implement it.  Otherwise I may get to this someday when I have spare time (which could be a very long time, or never).

**Comment by jroal** [comment] 2020-08-15 12:13
> I would just disable screen rotation on the activity config. Problem solved. 👍🏻

Perfect!  That is now my plan for all the rotation issues.  I will simply block all rotations as they are not needed for this app anyway.  Everything will now be forced portrait.

**Comment by jroal** [comment] 2020-08-15 12:20
Duplicate of issue 295 based on planned fix https://github.com/jroal/a2dpvolume/issues/295

**Closed as completed by jroal** 2020-08-15 12:20 UTC
Labels: bug, duplicate, help wanted, Priority-Low
