### ISSUE TITLE
Rotating the screen in the preferences interface will cause the app to crash

### ISSUE THREAD

**Issue by sjl872964789** [jroal/a2dpvolume#290] opened 2020-06-02 05:50 UTC
**Describe the bug**
Rotating the screen in the preferences interface will cause the app to crash

**To Reproduce**
1. Install a2dp and open app
2. Click three points in the upper right corner
3. Click "preferences"
4. Rotate screen
5. Crash

**Expected behavior**
Not crash

**Smartphone (please complete the following information):**
 - Device: HUAWEI nova 5 pro
 - OS: EMUI 9.1.1
 - Rooted: No
 - Version: v2.13.0.4

**Additional context**

**Comment by junior291492659** [comment] 2020-06-08 08:29
I have also encountered this issue. It would be really appreciated to get your concern on this.

**Comment by jroal** [comment] 2020-08-15 12:14
> I would just disable screen rotation on the activity config. Problem solved. 👍🏻

Perfect!  That is now my plan for all the rotation issues.  I will simply block all rotations as they are not needed for this app anyway.  Everything will now be forced portrait.

**Comment by jroal** [comment] 2020-08-15 12:21
Duplicate of issue 295 based on planned fix https://github.com/jroal/a2dpvolume/issues/295

**Closed as completed by jroal** 2020-08-15 12:21 UTC
Labels: bug, duplicate, help wanted, Priority-Low
