### ISSUE TITLE
an IllegalArgumentException crash

### ISSUE THREAD

**Issue by tingsu** [jroal/a2dpvolume#236] opened 2017-01-15 11:58 UTC
Hi a2dp, there is a crash we found:

 version: 2.8.11
 android SDK version: Android 4.4.2
 device: Android emulator
 crash stack:

  E/AndroidRuntime(19147): java.lang.RuntimeException: Unable to start activity ComponentInfo{a2dp.Vol/a2dp.Vol.EditDevice}: java.lang.IllegalArgumentException: the bind value at index 1 is null
E/AndroidRuntime(19147): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2211)
E/AndroidRuntime(19147): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2261)
E/AndroidRuntime(19147): 	at android.app.ActivityThread.access$600(ActivityThread.java:141)
E/AndroidRuntime(19147): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
E/AndroidRuntime(19147): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(19147): 	at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime(19147): 	at android.app.ActivityThread.main(ActivityThread.java:5103)
E/AndroidRuntime(19147): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(19147): 	at java.lang.reflect.Method.invoke(Method.java:525)
E/AndroidRuntime(19147): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
E/AndroidRuntime(19147): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
E/AndroidRuntime(19147): 	at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime(19147): Caused by: java.lang.IllegalArgumentException: the bind value at index 1 is null
E/AndroidRuntime(19147): 	at android.database.sqlite.SQLiteProgram.bindString(SQLiteProgram.java:164)
E/AndroidRuntime(19147): 	at android.database.sqlite.SQLiteProgram.bindAllArgsAsStrings(SQLiteProgram.java:200)
E/AndroidRuntime(19147): 	at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:47)
E/AndroidRuntime(19147): 	at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1314)
E/AndroidRuntime(19147): 	at android.database.sqlite.SQLiteDatabase.queryWithFactory(SQLiteDatabase.java:1161)
E/AndroidRuntime(19147): 	at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1032)
E/AndroidRuntime(19147): 	at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1238)
E/AndroidRuntime(19147): 	at a2dp.Vol.DeviceDB.getBTD(DeviceDB.java:142)
E/AndroidRuntime(19147): 	at a2dp.Vol.EditDevice.onCreate(EditDevice.java:174)
E/AndroidRuntime(19147): 	at android.app.Activity.performCreate(Activity.java:5133)
E/AndroidRuntime(19147): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
E/AndroidRuntime(19147): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2175)
E/AndroidRuntime(19147): 	... 11 more

**Comment by jroal** [comment] 2017-01-15 13:16
Thanks for the feedback.  2.8.11 is so old (August 2012) and I have not been able to reproduce this on the recent versions.  There have been many significant changes since 2.8.11.  Also, emulators can be very slow and they have no Bluetooth support.  I am going to close this issue.  I suggest you update to the latest version.

**Closed by jroal** 2017-01-15 13:16 UTC

**Comment by tingsu** [comment] 2017-01-15 13:45
Thanks for your quick reply and your efforts in developing this app, Jim.
